### PR TITLE
feat: add modulo controller interface package

### PR DESCRIPTION
**Pull request by domire8**
## Description

- #82 

This PR adds the `modulo_controller_interface` package with the `ModuloControllerInterface` class. My intention is to copy this class as is, merge into a feature branch and then work on additional features on that branch before going to main.

These files do not have any changes after porting except package name change, namespace change, and CMakeLists updates.

## Review guidelines

Estimated Time of Review: 4 minutes

## Checklist before merging:

- [ ] Confirm that the relevant changelog(s) are up-to-date in case of any user-facing changes

### CODE REVIEW

**Comment by domire8** [comment]
One could question the package name. For the components, we use `modulo_components` and not `modulo_component_interfaces`. However, we can only name this package `modulo_controllers` if we rename our internal controller package.

**Review by bpapaspyros — APPROVED** [review]
it would indeed be nicer to name this `modulo_controllers` but I am not sure we can do this without a big upset on other repositories. So, looks good to me, but I I'd wait for @eeberhard 's opinion

**Review by eeberhard — APPROVED** [review]
I agree that the package name should be `modulo_controllers`. This is going into a feature branch anyway, so I think it would be nice to migrate "as is" first and then refactor the package name separately. The added benefit is that we can migrate downstream controllers gradually using either the old (proprietary) package name or the new one instead.

**Review by eeberhard — APPROVED** [review]
🔥

**Pull request merged**
